# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

{% import 'macros.jinja' as macros with context %}

{{ macros.github_header() }}

jobs:
  build-cpp-ubuntu:
    name: Build C++ Gandiva Libs Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Arrow Directory
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/arrow
          key: gandiva-libs-${{ github.sha }}
      - name: Checkout Arrow
        run: |
          git clone --no-checkout {{ arrow.remote }} arrow
          git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
          if [ $CROSSBOW_USE_COMMIT_ID = true ]; then git -C arrow checkout {{ arrow.head }}; else git -C arrow checkout FETCH_HEAD; fi
          git -C arrow submodule update --init --recursive
      - name: Build Gandiva
        run: |
          python3 -VV
          cd arrow
          mkdir -p dist
          export CC="gcc-4.9" CXX="g++-4.9"
          ulimit -c unlimited -S
          set -e
          docker run -v $PWD:/arrow quay.io/anthonylouisbsb/arrow:gandivadocker /arrow/dev/tasks/gandiva-jars/build-cpp-linux.sh
          dev/tasks/gandiva-jars/check_shared_dependencies.sh
        env:
          OS_NAME: "linux"
          CHECK_SHARED_DEPENDENCIES: true
  build-cpp-macos:
    name: Build C++ Gandiva Libs MacOS
    runs-on: macos-latest
    needs: build-cpp-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Cache Arrow Directory
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/arrow
          key: gandiva-libs-${{ github.sha }}
      - name: Build Gandiva
        run: |
          cd arrow
          mkdir -p dist
          export ARROW_TEST_DATA=$PWD/testing/data
          set -e
          dev/tasks/gandiva-jars/build-cpp-osx.sh
          dev/tasks/gandiva-jars/check_shared_dependencies.sh
        env:
          OS_NAME: "osx"
          CHECK_SHARED_DEPENDENCIES: true
          MACOSX_DEPLOYMENT_TARGET: "10.11"
  package-jar-macos:
    # Checks if the gandiva jar is built correctly inside the MacOS
    # and if all the Gandiva tests are running fine in Java
    name: Build Gandiva Jar MacOS
    runs-on: macos-latest
    needs: [build-cpp-macos, build-cpp-ubuntu]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Arrow Directory
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/arrow
          key: gandiva-libs-${{ github.sha }} 
      - name: Build Gandiva Jar
        run: |
          cd arrow
          export ARROW_TEST_DATA=$PWD/testing/data
          set -e
          dev/tasks/gandiva-jars/build-java.sh
        env:
          OS_NAME: "osx"
          COPY_JAR_TO_DISTRIBUTION_FOLDER: false
          MACOSX_DEPLOYMENT_TARGET: "10.11"
  package-and-upload-jar-ubuntu:
    name: Package Gandiva Jar Ubuntu
    runs-on: ubuntu-18.04
    needs: [build-cpp-macos, build-cpp-ubuntu, package-jar-macos]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Arrow Directory
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/arrow
          key: gandiva-libs-${{ github.sha }}
      - name: Build Gandiva Jar
        run: |
          python3 -VV
          cd arrow
          ulimit -c unlimited -S
          set -e
          dev/tasks/gandiva-jars/build-java.sh
        env:
          OS_NAME: "linux"
          COPY_JAR_TO_DISTRIBUTION_FOLDER: true

      {{ macros.github_upload_releases("arrow/dist/*.jar")|indent }}