# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: MATLAB Packaging Workflow

on:
  push:
    paths:
      - '.github/workflows/matlab_package.yml'
      - 'ci/scripts/matlab*.sh'
      - 'matlab/**'
      - 'cpp/src/arrow/**'
  pull_request:
    paths:
      - '.github/workflows/matlab_package.yml'
      - 'ci/scripts/matlab*.sh'
      - 'matlab/**'
      - 'cpp/src/arrow/**'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  ubuntu:
    name: AMD64 Ubuntu 20.04 MATLAB
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install ninja-build
        run: sudo apt-get install ninja-build
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Install ccache
        run: sudo apt-get install ccache
      - name: Setup ccache
        shell: bash
        run: ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ${{ steps.ccache-info.outputs.cache-dir }}
          key: matlab-ccache-ubuntu-${{ hashFiles('cpp/**', 'matlab/**') }}
          restore-keys: matlab-ccache-ubuntu-
      - name: Build MATLAB Interface
        run: ci/scripts/matlab_build.sh $(pwd)
      - name: Compress into single artifact to keep directory structure
        run: tar -cvzf arrow-matlab-ubuntu.tar.gz matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-ubuntu.tar.gz
          path: arrow-matlab-ubuntu.tar.gz

  macos:
    name: AMD64 macOS 11 MATLAB
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install ninja-build
        run: brew install ninja
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Install ccache
        run: brew install ccache
      - name: Setup ccache
        shell: bash
        run: ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ${{ steps.ccache-info.outputs.cache-dir }}
          key: matlab-ccache-macos-${{ hashFiles('cpp/**', 'matlab/**') }}
          restore-keys: matlab-ccache-macos-
      - name: Build MATLAB Interface
        run: ci/scripts/matlab_build.sh $(pwd)
      - name: Compress into single artifact to keep directory structure
        run: tar -cvzf arrow-matlab-macos.tar.gz matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-macos.tar.gz
          path: arrow-matlab-macos.tar.gz

  windows:
    name: AMD64 Windows 2022 MATLAB
    runs-on: windows-2022
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    steps:
      - name: Check out repository        
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Download Timezone Database
        shell: bash
        run: ci/scripts/download_tz_database.sh
      - name: Install ccache
        shell: bash
        run: ci/scripts/install_ccache.sh 4.6.3 /usr
      - name: Setup ccache
        shell: bash
        run: ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.ccache-info.outputs.cache-dir }}
          key: matlab-ccache-windows-${{ hashFiles('cpp/**', 'matlab/**') }}
          restore-keys: matlab-ccache-windows-
      - name: Build MATLAB Interface
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          bash -c "ci/scripts/matlab_build.sh $(pwd)"
      - name: Compress into single artifact to keep directory structure
        shell: bash
        run: tar -cvzf arrow-matlab-windows.tar.gz matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-windows.tar.gz
          path: arrow-matlab-windows.tar.gz

  package-mltbx:
    name: Package MATLAB Toolbox (MLTBX) Files
    runs-on: ubuntu-latest
    needs:
      - ubuntu
      - macos
      - windows
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
            path: artifacts-downloaded
      - name: Decompress Artifacts
        run: |
            mv artifacts-downloaded/*/*.tar.gz .
            tar -xzvf arrow-matlab-ubuntu.tar.gz
            tar -xzvf arrow-matlab-macos.tar.gz
            tar -xzvf arrow-matlab-windows.tar.gz
      - name: Print Current Directory
        run: |
            pwd && ls && tree /
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
            release: R2023a
      - name: Run commands
        env:
            MATLABPATH: matlab/tools
            ARROW_MATLAB_TOOLBOX_FOLDER: .
            ARROW_MATLAB_TOOLBOX_OUTPUT_FOLDER: artifacts
            ARROW_MATLAB_TOOLBOX_VERSION: 15.0.0
        uses: matlab-actions/run-command@v1
        with:
            command: packageMatlabInterface
