# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

{% import 'macros.jinja' as macros with context %}

{{ macros.github_header() }}

jobs:

  ubuntu:
    name: AMD64 Ubuntu 20.04 MATLAB
    runs-on: ubuntu-latest
    steps:
      {{ macros.github_checkout_arrow()|indent }}
      - name: Install ninja-build
        run: sudo apt-get update && sudo apt-get install ninja-build
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Build MATLAB Interface
        env:
        {{ macros.github_set_sccache_envvars()|indent(8) }}
        run: arrow/ci/scripts/matlab_build.sh $(pwd)/arrow
      - name: Compress into single artifact to keep directory structure
        run: tar -cvzf arrow-matlab-ubuntu.tar.gz arrow/matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-ubuntu.tar.gz
          path: arrow-matlab-ubuntu.tar.gz

  macos:
    name: AMD64 macOS 11 MATLAB
    runs-on: macos-latest
    steps:
      {{ macros.github_checkout_arrow()|indent }}
      - name: Install ninja-build
        run: brew install ninja
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Build MATLAB Interface
        env:
        {{ macros.github_set_sccache_envvars()|indent(8) }}
        run: arrow/ci/scripts/matlab_build.sh $(pwd)/arrow
      - name: change shared library install name
        run: |
           pushd arrow/matlab/install/arrow_matlab/+libmexclass/+proxy
           SYMLINK_ARROW_LIB="$(find . -regex "./libarrow.[0-9][0-9][0-9][0-9].dylib" | xargs basename)"
           REGULAR_ARROW_LIB="$(find . -regex "./libarrow.[0-9][0-9][0-9][0-9].[0-9].[0-9].dylib" | xargs basename)"
           install_name_tool -change @rpath/$SYMLINK_ARROW_LIB @rpath/$REGULAR_ARROW_LIB libarrowproxy.dylib
           popd
      - name: Compress into single artifact to keep directory structure
        run: tar -cvzf arrow-matlab-macos.tar.gz arrow/matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-macos.tar.gz
          path: arrow-matlab-macos.tar.gz

  windows:
    name: AMD64 Windows 2022 MATLAB
    runs-on: windows-2022
    steps:
      {{ macros.github_checkout_arrow()|indent }}
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Download Timezone Database
        shell: bash
        run: arrow/ci/scripts/download_tz_database.sh
      - name: Install sccache
        shell: bash
        run: arrow/ci/scripts/install_sccache.sh pc-windows-msvc $(pwd)/sccache
      - name: Build MATLAB Interface
        shell: cmd
        env:
        {{ macros.github_set_sccache_envvars()|indent(8) }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          bash -c "arrow/ci/scripts/matlab_build.sh $(pwd)/arrow"
      - name: Compress into single artifact to keep directory structure
        shell: bash
        run: tar -cvzf arrow-matlab-windows.tar.gz arrow/matlab/install/arrow_matlab
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arrow-matlab-windows.tar.gz
          path: arrow-matlab-windows.tar.gz

  package-mltbx:
    name: Package MATLAB Toolbox (MLTBX) Files
    runs-on: ubuntu-latest
    needs:
      - ubuntu
      - macos
      - windows
    steps:
      {{ macros.github_checkout_arrow(fetch_depth=0)|indent }}
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts-downloaded
      - name: Decompress Artifacts
        run: |
          mv artifacts-downloaded/*/*.tar.gz .
          tar -xzvf arrow-matlab-ubuntu.tar.gz
          tar -xzvf arrow-matlab-macos.tar.gz
          tar -xzvf arrow-matlab-windows.tar.gz
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a
      - name: Run commands
        env:
          MATLABPATH: arrow/matlab/tools
          ARROW_MATLAB_TOOLBOX_FOLDER: arrow/matlab/install/arrow_matlab
          ARROW_MATLAB_TOOLBOX_OUTPUT_FOLDER: artifacts/matlab-dist
          ARROW_MATLAB_TOOLBOX_VERSION: {{ arrow.no_rc_version }}
        uses: matlab-actions/run-command@v1
        with:
          command: packageMatlabInterface
      {{ macros.github_upload_releases(["artifacts/matlab-dist/*.mltbx"])|indent }}
