# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Operating system (build VM template)
os: Visual Studio 2015

only_commits:
  # Skip commits not related to Python, C++ or Rust
  files:
    - appveyor.yml
    - ci/
    - cpp/
    - python/
    - rust/

cache:
  - C:\Users\Appveyor\clcache
  - C:\Users\Appveyor\.cargo\registry

environment:
  global:
    BUILD_SCRIPT: "CPP_MSVC"
    USE_CLCACHE: true

  matrix:
    # NOTE: clcache seems to work best with Ninja and worst with msbuild
    # (as generated by cmake)
    - JOB: "Build"
      GENERATOR: Ninja
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Release"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:\Libraries\boost_1_64_0
    - JOB: "Build_Debug"
      GENERATOR: Ninja
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Debug"
    - JOB: "Build"
      GENERATOR: Ninja
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Release"
    - JOB: "Static_Crt_Build"
      GENERATOR: Ninja
      PYTHON: "3.6"
      ARCH: "64"
    - JOB: "Toolchain"
      GENERATOR: Visual Studio 14 2015 Win64
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Release"
    - JOB: "Cmake_Script_Tests"
      GENERATOR: NMake Makefiles
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Release"
      BUILD_SCRIPT: "CMake_Build_Script"
    - JOB: "Build"
      GENERATOR: NMake Makefiles
      PYTHON: "3.6"
      ARCH: "64"
      CONFIGURATION: "Release"
    - JOB: "Rust_Stable"
      RUST_VERSION: stable
      TARGET: x86_64-pc-windows-msvc
      BUILD_SCRIPT: "Rust_Stable"
      USE_CLCACHE: false

  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib64-msvc-14.0
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - if NOT "%JOB%"=="Rust_Stable" set MINICONDA=C:\Miniconda36-x64
  - if NOT "%JOB%"=="Rust_Stable" set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%
  - if NOT "%JOB%"=="Rust_Stable" call ci\appveyor-setup.bat
  - if "%JOB%"=="Rust_Stable" curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - if "%JOB%"=="Rust_Stable" rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - if "%JOB%"=="Rust_Stable" set PATH=%PATH%;C:\Users\Appveyor\.cargo\bin
  - if "%JOB%"=="Rust_Stable" rustc -Vv
  - if "%JOB%"=="Rust_Stable" cargo -V

build_script:
  - git config core.symlinks true
  - git reset --hard
  - if "%BUILD_SCRIPT%"=="CMake_Build_Script" call ci\test-cmake-build-script.bat
  - if "%BUILD_SCRIPT%"=="CPP_MSVC" call ci\cpp-python-msvc-build.bat
  - if "%BUILD_SCRIPT%"=="Rust_Stable" call ci\rust-msvc-build.bat

# Disable test discovery
test: off

after_build:
  - if "%USE_CLCACHE%" == "true" clcache -s
