# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

{% import 'macros.jinja' as macros with context %}

dist: focal

language: minimal

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.docker

addons:
  apt:
    packages:
      - python3-pip

services:
  - docker

# Note that the global "env" setting isn't inherited automatically by
# matrix entries with their own "env", so we have to insert it explicitly.
env: &global_env
  ARROW_ENABLE_TIMING_TESTS: "OFF"
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 0
  DOCKER_VOLUME_PREFIX: $TRAVIS_BUILD_DIR/.docker/

jobs:
  include:
    - name: "Docker Test {{ image }} {{ architecture|default("") }}"
      os: linux
      arch: "{{ architecture|default("") }}"
      group: edge
      virt: vm
      {{ macros.github_set_env(env) }}
        <<: *global_env   
    runs-on: ubuntu-latest

before_script:
  - set -e
  {{ macros.travis_checkout_arrow() }}
  {{ macros.travis_docker_login() }}

script:
  # Install Archery and Crossbow dependencies
  {{ macros.travis_install_archery() }}

  # Build and Test
  # output something every minutes to prevent travis from killing the build
  - while sleep 1m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - archery docker run {{ image }}
  - kill %1
