jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  steps:
    # for deployment
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.6'

    # for building the linux packages
    - task: UseRubyVersion@0
      inputs:
        addToPath: true

    - script: |
        git clone --no-checkout {{ arrow.remote }} arrow
        git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
        git -C arrow checkout FETCH_HEAD
        git -C arrow submodule update --init --recursive
      displayName: Clone arrow

    - script: |
        pushd arrow/dev/tasks/linux-packages
        rake version:update
        rake dist
        {{ build_command }}
        popd

    # Using github release tries to find a common ancestor between the
    # currently pushed tag and the latest tag of the github repository
    # (don't know why).
    # The tag upload took 43 minutes because of this scan, so use an
    # alternative upload script.
    - script: |
        conda install -y --file arrow/ci/conda_env_crossbow.txt
        python crossbow.py upload-assets \
          --sha {{ task.branch }} \
          --tag {{ task.tag }} \
        {% for extension in upload_extensions -%}
          --pattern "**/*{{ extension }}"
        {% endfor -%}
      env:
        CROSSBOW_GITHUB_REPO: $(Build.Repository.Name)
        CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
      displayName: Upload packages as a GitHub release
      workingDirectory: arrow/dev/tasks
