# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

os: linux
dist: trusty
sudo: required
language: ruby

# don't build twice
if: tag IS blank

env:
  global:
    - PLAT=x86_64
    - TRAVIS_TAG={{ task.tag }}
    - ARROW_VERSION={{ arrow.version }}

before_install:
{%- if arrow.source == 'git' %}
  - git clone -b {{ arrow.branch }} {{ arrow.remote }} arrow
  - git -C arrow checkout {{ arrow.head }}
{%- elif arrow.source == 'dist' %}
  - curl -OL {{ arrow.archive_url }}
  {%- if arrow.verify %}
  - curl -OL {{ arrow.checksum_url }}
  - shasum -a 256 -c {{ arrow.checksum_filename }}
  {%- endif %}
  - mkdir arrow
  - tar -xzvf {{ arrow.archive_filename }} --strip-components=1 -C arrow
  - mv {{ arrow.archive_filename }} arrow/dev/tasks/linux-packages/
{%- endif %}

install:
  - sudo apt update -y -qq
  - |
    sudo apt install -y -qq \
        autoconf-archive \
        build-essential \
        cmake \
        debhelper \
        devscripts \
        git \
        gtk-doc-tools \
        libboost-filesystem-dev \
        libboost-regex-dev \
        libboost-system-dev \
        libgirepository1.0-dev \
        libglib2.0-doc \
        libjemalloc-dev \
        lsb-release \
        nvidia-cuda-toolkit \
        pkg-config \
        python3-dev \
        python3-numpy

script:
  - pushd arrow/dev/tasks/linux-packages
{%- if arrow.source == 'git' %}
  - rake dist
{%- endif %}
  - {{ build_command }}

deploy:
  provider: releases
  api_key: $CROSSBOW_GITHUB_TOKEN
  file_glob: true
  file:
  {% for extension in upload_extensions -%}
    - "**/*{{ extension }}"
  {% endfor -%}
  skip_cleanup: true
  on:
    tags: true

{% if job.email %}
notifications:
  email:
    - {{ job.email }}
{% endif %}
