[package]
name = "flight"
description = "Flight server"
version = "1.0.0-SNAPSHOT"
edition = "2018"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
homepage = "https://github.com/apache/arrow"
repository = "https://github.com/apache/arrow"
license = "Apache-2.0"

[dependencies]
tonic = "0.1.0-alpha.5"
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
tokio = "=0.2.0-alpha.6"

[build-dependencies]
tonic-build = "0.1.0-alpha.5"
