{% import 'macros.jinja' as macros with context %}

jobs:
- job: win
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  variables:
    CONFIG: {{ config }}
    R_CONFIG: {{ r_config|default("") }}
    ARROW_VERSION: {{ arrow.no_rc_version }}
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_PACKAGES: False

  steps:
    - script: |
        choco install vcpython27 -fdv -y --debug
      condition: contains(variables['CONFIG'], 'vs2008')
      displayName: Install vcpython27.msi (if needed)

    - powershell: |
        Set-PSDebug -Trace 1
        $batchcontent = @"
        ECHO ON
        SET vcpython=C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0
        DIR "%vcpython%"
        CALL "%vcpython%\vcvarsall.bat" %*
        "@
        $batchDir = "C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC"
        $batchPath = "$batchDir" + "\vcvarsall.bat"
        New-Item -Path $batchPath -ItemType "file" -Force
        Set-Content -Value $batchcontent -Path $batchPath
        Get-ChildItem -Path $batchDir
        Get-ChildItem -Path ($batchDir + '\..')
      condition: contains(variables['CONFIG'], 'vs2008')
      displayName: Patch vs2008 (if needed)

    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.6 conda-build conda conda-forge::conda-forge-ci-setup=3 pip' # Optional
        installOptions: "-c conda-forge"
        updateConda: true
      displayName: Install conda-build and activate environment
    - script: set PYTHONUNBUFFERED=1

    {{ macros.azure_checkout()|indent(2) }}

    # Configure the VM
    - script: setup_conda_rc .\ .\ .\.ci_support\%CONFIG%.yaml
      workingDirectory: arrow\dev\tasks\conda-recipes

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup
      workingDirectory: arrow\dev\tasks\conda-recipes

    - script: |
        conda.exe build arrow-cpp parquet-cpp -m .ci_support\%CONFIG%.yaml
      displayName: Build recipe
      workingDirectory: arrow\dev\tasks\conda-recipes
      env:
        PYTHONUNBUFFERED: 1
      condition: not(contains(variables['CONFIG'], 'vs2008'))

    - script: |
        conda.exe build r-arrow -m .ci_support\r\%R_CONFIG%.yaml
      displayName: Build recipe
      workingDirectory: arrow\dev\tasks\conda-recipes
      env:
        PYTHONUNBUFFERED: 1
      condition: contains(variables['R_CONFIG'], 'win')

    {{ macros.azure_upload("D:\bld\win-64\*.tar.bz2")|indent(2) }}

    {% if arrow.branch == 'master' %}
    # Upload to custom anaconda channel
    - script: |
        source activate base
        conda install -y anaconda-client
        anaconda -t $(CROSSBOW_ANACONDA_TOKEN) upload --force D:\bld\win-64\*.tar.bz2
      displayName: Upload packages to Anaconda
      workingDirectory: arrow/dev/tasks/conda-recipes
    {% endif %}
