os: linux
dist: trusty
language: generic

# don't build twice
if: tag IS blank

env:
  global:
    - TRAVIS_TAG={{ task.tag }}
    - ARROW_VERSION={{ arrow.no_rc_version }}
    - PYTHONUNBUFFERED=1

install:
  # Install Miniconda.
  - echo `pwd`
  - |
    echo ""
    echo "Installing a fresh version of Miniconda."
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b

  # Install conda build dependency
  - |
    echo ""
    echo "Configuring conda."
    source /home/travis/miniconda3/bin/activate root
    conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build

before_script:
  - git clone --no-checkout {{ arrow.remote }} arrow
  - git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
  - git -C arrow checkout FETCH_HEAD

  - pushd arrow/dev/tasks/conda-recipes

  # Configure conda
  - setup_conda_rc ./ ./ .ci_support/{{ config }}.yaml
  - source run_conda_forge_build_setup

script:
  - |
    conda build --croot $TRAVIS_HOME/conda_build_root \
                --output-folder . \
                -m .ci_support/{{ config }}.yaml \
                parquet-cpp arrow-cpp pyarrow

deploy:
  provider: releases
  api_key: $CROSSBOW_GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/arrow/dev/tasks/conda-recipes/linux-64/*.tar.bz2
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - {{ job.email }}
