name: Julia
on:
  push:
    paths:
      - '.github/workflows/julia.yml'
      - 'ci/docker/*_julia.dockerfile'
      - 'ci/scripts/julia_*'
      - 'julia/**'
  pull_request:
    paths:
      - '.github/workflows/julia.yml'
      - 'ci/docker/*_julia.dockerfile'
      - 'ci/docker/**'
      - 'ci/scripts/julia_*'
      - 'julia/**'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    env:
      JULIA_NUM_THREADS: 2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1' # automatically expands to the latest stable 1.x release of Julia
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-runtest@v1
        with:
          project: julia/Arrow
