name: Rust

on:
  push:
    paths:
      - 'rust/arrow/*'
      - 'rust/arrow/*/*'
      - 'rust/arrow/*/*/*'
      - 'rust/arrow/*/*/*/*'
      - 'rust/arrow/*/*/*/*/*'
      - 'rust/parquet/*'
      - 'rust/parquet/*/*'
      - 'rust/parquet/*/*/*'
      - 'rust/parquet/*/*/*/*'
      - 'rust/parquet/*/*/*/*/*'
      - 'rust/datafusion/*'
      - 'rust/datafusion/*/*'
      - 'rust/datafusion/*/*/*'
      - 'rust/datafusion/*/*/*/*'
      - 'rust/datafusion/*/*/*/*/*'
  pull_request:
    paths:
      - 'rust/arrow/*'
      - 'rust/arrow/*/*'
      - 'rust/arrow/*/*/*'
      - 'rust/arrow/*/*/*/*'
      - 'rust/arrow/*/*/*/*/*'
      - 'rust/parquet/*'
      - 'rust/parquet/*/*'
      - 'rust/parquet/*/*/*'
      - 'rust/parquet/*/*/*/*'
      - 'rust/parquet/*/*/*/*/*'
      - 'rust/datafusion/*'
      - 'rust/datafusion/*/*'
      - 'rust/datafusion/*/*/*'
      - 'rust/datafusion/*/*/*/*'
      - 'rust/datafusion/*/*/*/*/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - name: Check Formatting
      run: cargo +stable fmt --all -- --check
    - name: Build
      run: |
        cd rust
        cargo build
    - name: Test
      run: |
        export ARROW_TEST_DATA=`pwd`/testing/data/
        export PARQUET_TEST_DATA=`pwd`/cpp/submodules/parquet-testing/data
        cd rust
        cargo test
    - name: Arrow Examples
        cd rust/arrow
        cargo run --example builders
        cargo run --example dynamic_types
        cargo run --example read_csv
        cargo run --example read_csv_infer_schema
    - name: DataFusion Examples
        cd rust/datafusion
        cargo run --example csv_sql
        cargo run --example parquet_sql
