name: "Windows MSVC"
on:
  - push
  - pull_request
jobs:
  latest:
    strategy:
      matrix:
        include:
          - os: windows-2019
            vs: 2019
        fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        submodules: true
      - name: CMake
        run: |
          mkdir build\cpp
          cmake ^
            -G "Visual Studio 16 2019" ^
            -A x64 ^
            -DARROW_USE_GLOG=OFF ^
            -DARROW_WITH_LZ4=OFF ^
            -DCMAKE_INSTALL_PREFIX=install ^
            -S cpp ^
            -B build\cpp
      - name: Install
        run: |
          cmake --build build\cpp --config Debug --target Install
